Project 4: add "join table" for visits
sarazaToussaint/vet_clinic pull request #4
Opened 2022-07-14 14:58 UTC by sarazaToussaint

## In this pull request I: 

- Use different types of relationships between tables.
- Prepare complex queries that answer analytical questions.
- Use primary key & foreign key mechanisms for joining tables.

     ### Queries' Screenshots

1. Who was the last animal seen by William Tatcher?
![Day4One](https://user-images.githubusercontent.com/34794815/179011578-c1893be4-c411-4bc9-839c-37296ac3bfbf.png)

2. How many different animals did Stephanie Mendez see?
![Day4Two](https://user-images.githubusercontent.com/34794815/179012109-1169ad57-e31d-4d1e-91e3-d2dac94270d5.png)

3. List all vets and their specialties, including vets with no specialties.
![Day4Three](https://user-images.githubusercontent.com/34794815/179012280-466a7909-c58c-4b0d-9b17-285b006502ec.png)

4. List all animals that visited Stephanie Mendez between April 1st and August 30th, 2020.
![Day4Four](https://user-images.githubusercontent.com/34794815/179012427-060525d2-ab90-4521-a329-f380b2c7358b.png)

5. What animal has the most visits to vets?
![Day4Five](https://user-images.githubusercontent.com/34794815/179012539-c40e1436-55ff-4afc-bd6e-8c4515a17ca1.png)

6. Who was Maisy Smith's first visit?
![Day4Six](https://user-images.githubusercontent.com/34794815/179012678-05ede125-b624-4e3c-9121-2580011d95eb.png)

7. Details for most recent visit: animal information, vet information, and date of visit.
![Day4Seven](https://user-images.githubusercontent.com/34794815/179012798-7b26d8ea-3058-4399-8be9-b94bf5e53fc2.png)

8. How many visits were with a vet that did not specialize in that animal's species?
![Day4Eight](https://user-images.githubusercontent.com/34794815/179012932-e87cdc8c-02b4-4113-94b2-c8f0ab00b8ed.png)

9. What specialty should Maisy Smith consider getting? Look for the species she gets the most.
![Day4Nine](https://user-images.githubusercontent.com/34794815/179013049-f44a02c5-b570-4127-98fe-54d5b7bb2817.png)

2022-07-14 15:11 UTC, Mre55 requested changes
**Hi @sarazaToussaint,**

You have done a great job so far! 💪 👏 
You still need to work on a few issues before moving on to the next project, but you're almost there!

## To highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- All queries are written and result as expected ✅
- The PR title and description are professional and descriptive ✅ 
- The README is well documented ✅ 

## Required Changes ♻️🛠️ 
_Check the comments under the review._

<img width="430" src="https://media1.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>


## Optional suggestions 🟡 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-14 15:11 UTC, Mre55 commented on data.sql
>  UPDATE animals SET owner_id = 5 WHERE name IN ('Angemon','Boarmon');
This `UPDATE` are changing the table so from line 38 - 46 should have to be moved in to the `schema.sql` file. Kindly, move those to keep the file structure professional.

2022-07-14 15:22 UTC, sarazaToussaint commented on data.sql
>  UPDATE animals SET owner_id = 5 WHERE name IN ('Angemon','Boarmon');
Hi @Mre55, I made the changes, thank you for the code review.

2022-07-14 15:24 UTC, KayLemba approved these changes
# STATUS: APPROVED :green_circle: :clap: 

Hello  @sarazaToussaint      , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

HIGHLIGHTS:

- Your project is professional 
- Your repo is professional 
- Well structured files 


Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-20 08:17 UTC, merged

2023-06-07 13:04 UTC, sarazaToussaint commented
Hi @KayLemba, thank you for the code review.